### ISSUE TITLE
Github site does not publish the Related terms box for all Glossary terms

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#59] opened 2022-08-05 16:11 UTC
There is a glitch with the Github site that means that it does not publish the Related Terms box, even though the related terms are all listed on the Airtable record. Please can you investigate and fix this across the whole database. The whole database appears to be affected by this issue. 

In addition to the issues that identify this issue, affected terms I have found where there is no related terms box published (when it should be published) are: 

Net Zero Target 
Net Zero Transition Plan 
Offsetting
Offset Provider
Offsetting Strategy
Paris Agreement Goals 
Residual Emissions

I've stopped looking now. The problem affects all Related Terms box

**Comment by Simone-TCLP** [comment] 2022-08-05 16:13
Here's an example of the TCLP glossary pag
<img width="391" alt="Screenshot 2022-08-05 at 17 07 31" src="https://user-images.githubusercontent.com/104088714/183118160-3bf186bb-98fc-47ea-a835-796b668bcb14.png">
e

Here's what it looks like on the Github page: 
<img width="499" alt="Screenshot 2022-08-05 at 17 12 24" src="https://user-images.githubusercontent.com/104088714/183118253-b21a55eb-546c-46f8-95cd-0d427d2a7746.png">

**Comment by akariv** [comment] 2022-08-07 16:51
Duplicate of #48

**Closed by akariv** 2022-08-07 16:51 UTC
