### ISSUE TITLE
Residual Emissions - missing related terms box

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#55] opened 2022-08-01 13:50 UTC
The box 'related terms' is missing from the Github page for Residual Emissions. The related terms are all in Airtable. They are also each linked to the term 'Residual Emissions'. The related terms are: Offsetting, GHG Emissions and Carbon Footprint.

1. This is [chancerylaneproject.org](https://chancerylaneproject.org/glossary/residual-emissions/
<img width="359" alt="Screenshot 2022-08-01 at 15 47 41" src="https://user-images.githubusercontent.com/104088714/182162899-9b879ab9-76d0-473b-a468-cdc0be51131b.png">

2. This is the Github page: 
<img width="419" alt="Screenshot 2022-08-01 at 15 49 39" src="https://user-images.githubusercontent.com/104088714/182162722-4d1e3d08-06fe-42f1-80eb-d3231051c940.png">

**Comment by akariv** [comment] 2022-08-07 16:49
Duplicate of #48

**Closed by akariv** 2022-08-07 16:49 UTC
