### ISSUE TITLE
Net Zero - missing Related Terms box

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#56] opened 2022-08-05 15:59 UTC
TCLP glossary entry for Net Zero contains a related terms box (see screenshot).
<img width="355" alt="Screenshot 2022-08-05 at 16 58 43" src="https://user-images.githubusercontent.com/104088714/183115914-2e3b5e69-a0f8-47ba-8981-7b67e5c159ac.png">

this is missing from the Net Zero glossary term page on Github.

All terms are in Airtable and should appear here.

**Comment by akariv** [comment] 2022-08-07 16:49
Duplicate of #48

**Closed by akariv** 2022-08-07 16:49 UTC
