### ISSUE TITLE
Net Zero Target - missing Related Terms box

### ISSUE THREAD

**Issue by Simone-TCLP** [TCLP-UoC/Glossary#57] opened 2022-08-05 16:04 UTC
TCLP glossary term Net Zero Target contains a related terms box (see screenshot): 
<img width="366" alt="Screenshot 2022-08-05 at 17 04 03" src="https://user-images.githubusercontent.com/104088714/183116752-45d2803c-45be-49e2-abe7-cec71aa99c16.png">

github page does not have this box even though all related terms are on airtable.

**Comment by akariv** [comment] 2022-08-07 16:50
Duplicate of #48

**Closed by akariv** 2022-08-07 16:50 UTC
